### ISSUE TITLE
won't load in 2.16 or 2.14

### ISSUE THREAD

**Issue by gubuntu** [mauroalberti/qProf#3]
Couldn't load plugin 'qProf' 

ImportError: cannot import name NavigationToolbar2QTAgg 
Traceback (most recent call last):
  File "/usr/local/qgis-2.16/share/qgis/python/qgis/utils.py", line 308, in loadPlugin
    **import**(packageName)
  File "/usr/local/qgis-2.16/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/qProf/__init__.py", line 24, in 
    from qProf_gui import qProf_gui
  File "/usr/local/qgis-2.16/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/qProf/qProf_gui.py", line 5, in 
    from qProf_QWidget import qprof_QWidget
  File "/usr/local/qgis-2.16/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/qProf/qProf_QWidget.py", line 49, in 
    from mpl.mpl_widget import MplWidget, plot_line, plot_filled_line
  File "/usr/local/qgis-2.16/share/qgis/python/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/gavin/.qgis2/python/plugins/qProf/mpl/mpl_widget.py", line 19, in 
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar
ImportError: cannot import name NavigationToolbar2QTAgg

Python version: 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609] 
QGIS version: 2.16.0-Nødebo Nødebo, b09eef1 

Ubuntu xenial

**Comment by mauroalberti** [comment]
Modified code for managing Matplotlib 1.5.0 API break. 
Loaded patched vers. 0.3.2 in QGIS Plugin repository, waiting for approval.
Current code in master will become vers. 0.3.3 - to be released end July-first half August.
